name: 'Test Build'

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Git LFS file list
        # This file will contain hashes of
        # every Git LFS file we need.
        # It will then be used to create
        # another hash which will serve
        # as the cache key.
        run: |
          git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
        shell: bash
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: .git/lfs
          # Increment the version suffix if you
          # need to manually invalidate the cache.
          key: v1-${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
          restore-keys: v1-${{ runner.os }}-lfs-
      - name: LS after cache
        run: ls
        shell: bash
      - name: Pull Git LFS Files
        run: GIT_TRACE=1 git lfs pull
        shell: bash
      - name: LS after Git LFS pull
        run: ls
        shell: bash